services:
  vityas-life:
    image: ${IMAGE_NAME:-ghcr.io/markusviktor/vityas-life}:${IMAGE_TAG:-master}
    container_name: vityas-life
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-8080}:80"
